services:
  postgres:
    image: postgres:latest
    container_name: the_data_xi_postgres 
    restart: always 
    environment:                   
      POSTGRES_USER: the_data_xi       
      POSTGRES_PASSWORD: the_data_xi    
      POSTGRES_DB: the_data_xi          
    ports:
      - "5432:5432"                  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:                 
