/* trivial tier (team-grain): RAW already typed -> passthrough + uids. */
select
    s.whoscored_match_id,
    s.combo_id,
    s.team_id,
    s.progressive_passes,
    s.passes_entering_final_third,
    s.passes_in_final_third,
    s.passes_in_final_third_accurate,
    s.passes_in_final_third_open_play,
    s.passes_in_final_third_op_accurate,
    s.penalty_area_passes,
    s.switches_of_play,
    s.avg_pass_length,
    s.avg_pass_length_euclid,
    s.avg_vertical_gain,
    s.forward_pass_pct,
    s.backward_pass_pct,
    s.lateral_pass_pct,
    s.directness_index,
    s.xt_total,
    s.xt_positive,
    s.xt_per_pass,
    s.key_passes,
    s.key_passes_open_play,
    s.assists,
    s.assists_open_play,
    s.chances_created,
    s.chances_created_open_play,
    s.big_chances_created,
    s.big_chances_created_open_play,
    s.crosses_open_play_attempted,
    s.crosses_open_play_accurate,
    s.corner_deliveries_open_play,
    s.ppda,
    s.field_tilt_pct,
    s.avg_release_seconds,
    s.quick_pass_pct,
    s.slow_pass_pct,
    coalesce(tx.team_uid, s.team_id) as team_uid
from {{ source('raw','ws_team_passing_adv') }} s
left join {{ ref('int_team_xwalk') }} tx on tx.ws_team_id = s.team_id
