/* trivial tier (player-grain): RAW already typed -> passthrough + uids. */
select
    s.combo_id,
    s.whoscored_match_id,
    s.event_id,
    s.team_id,
    s.player_id,
    s.player_name,
    s.minute,
    s.second,
    s.expanded_minute,
    s.period,
    s.x,
    s.y,
    s.is_goal,
    s.is_on_target,
    s.is_blocked,
    s.is_off_target,
    s.is_open_play,
    s.location,
    s.in_box,
    s.six_yard_box,
    s.small_box,
    s.distance_m,
    s.angle_deg,
    s.body_part,
    s.is_header,
    s.is_right_foot,
    s.is_left_foot,
    s.is_volley,
    s.is_first_touch,
    s.pattern,
    s.is_from_corner,
    s.is_from_freekick,
    s.is_fast_break,
    s.is_assisted,
    s.is_individual_play,
    s.is_big_chance,
    s.is_one_on_one,
    s.goal_mouth_y,
    s.goal_mouth_z,
    s.placement,
    s.related_event_id,
    s.xgot,
    s.sca_1_player_id,
    s.sca_1_player_name,
    s.sca_1_type,
    s.sca_2_player_id,
    s.sca_2_player_name,
    s.sca_2_type,
    coalesce(px.player_uid, s.player_id) as player_uid,
    coalesce(tx.team_uid, s.team_id) as team_uid
from {{ source('raw','ws_shots') }} s
left join {{ ref('int_player_xwalk') }} px on px.ws_player_id = s.player_id
left join {{ ref('int_team_xwalk') }} tx on tx.ws_team_id = s.team_id
