/* trivial tier (player-grain): RAW already typed -> passthrough + uids. */
select
    s.whoscored_match_id,
    s.combo_id,
    s.team_id,
    s.player_id,
    s.player_name,
    s.saves,
    s.goals_conceded,
    s.shots_on_target_faced,
    s.save_pct,
    s.saves_standing,
    s.saves_diving,
    s.saves_in_box,
    s.saves_out_of_box,
    s.saves_collected,
    s.saves_parried_safe,
    s.saves_parried_danger,
    s.saves_with_head,
    s.saves_other_body_part,
    s.keeper_pickups,
    s.pickups_routine,
    s.pickups_after_save,
    s.high_claims,
    s.high_claims_won,
    s.high_claim_win_pct,
    s.sweeper_actions,
    s.avg_sweeper_x,
    s.punches,
    s.punches_accurate,
    s.avg_punch_distance_m,
    s.distributions_total,
    s.passes_total,
    s.passes_accurate,
    s.distribution_accuracy_pct,
    s.goal_kicks,
    s.keeper_throws,
    s.longballs,
    s.longballs_accurate,
    s.longball_accuracy_pct,
    s.short_passes,
    s.freekick_passes,
    s.avg_distribution_length_m,
    s.long_kick_pct,
    s.short_kick_pct,
    s.touches_outside_box,
    s.passes_outside_box,
    s.clearances,
    s.progressive_passes,
    coalesce(px.player_uid, s.player_id) as player_uid,
    coalesce(tx.team_uid, s.team_id) as team_uid
from {{ source('raw','ws_player_goalkeep') }} s
left join {{ ref('int_player_xwalk') }} px on px.ws_player_id = s.player_id
left join {{ ref('int_team_xwalk') }} tx on tx.ws_team_id = s.team_id
