/* trivial tier (team-grain): RAW already typed -> passthrough + uids. */
select
    s.combo_id,
    s.whoscored_match_id,
    s.team_id,
    s.passing_rate,
    s.passes_accurate,
    s.possession_minutes,
    s.field_tilt_pct,
    s.field_tilt_passes_pct,
    s.final_third_touches,
    s.ppda,
    s.sequences_total,
    s.open_play_sequences,
    s.avg_sequence_time_s,
    s.avg_sequence_length,
    s.passes_per_sequence,
    s.start_distance_m,
    s.direct_speed_m_s,
    s.ten_plus_pass_sequences,
    s.build_up_attacks,
    s.direct_attacks,
    s.high_turnovers,
    s.high_turnover_shots,
    s.shot_sequences,
    s.shot_seq_pct,
    s.avg_shot_seq_length,
    s.avg_shot_seq_duration_s,
    s.avg_shot_seq_passes,
    s.attack_sequences,
    s.avg_attack_duration_s,
    s.avg_attack_passes,
    s.possessions_total,
    s.avg_possession_duration_s,
    s.avg_sequences_per_possession,
    s.counter_attack_sequences,
    s.counter_attack_shot_pct,
    s.open_play_turnover_pct,
    s.possession_loss_pct,
    s.set_piece_end_pct,
    coalesce(tx.team_uid, s.team_id) as team_uid
from {{ source('raw','ws_team_poss_adv') }} s
left join {{ ref('int_team_xwalk') }} tx on tx.ws_team_id = s.team_id
