/* trivial tier (team-grain): RAW already typed -> passthrough + uids. */
select
    s.whoscored_match_id,
    s.combo_id,
    s.team_id,
    s.passes_total,
    s.passes_accurate,
    s.passes_inaccurate,
    s.pass_accuracy_pct,
    s.longballs_attempted,
    s.longballs_accurate,
    s.longball_accuracy_pct,
    s.throughballs,
    s.head_passes,
    s.layoffs,
    s.passes_short,
    s.passes_medium,
    s.passes_long_band,
    s.freekick_passes,
    s.indirect_fk_passes,
    s.goalkick_passes,
    s.crosses_attempted,
    s.crosses_accurate,
    s.cross_accuracy_pct,
    s.corner_deliveries,
    s.corner_deliveries_accurate,
    s.throwins_attempted,
    s.throwins_accurate,
    s.keeper_throws_attempted,
    s.keeper_throws_accurate,
    s.blocked_passes,
    s.key_passes,
    s.assists,
    s.big_chances_created,
    s.passes_entering_final_third,
    s.passes_in_final_third,
    s.passes_in_final_third_accurate,
    coalesce(tx.team_uid, s.team_id) as team_uid
from {{ source('raw','ws_team_passing') }} s
left join {{ ref('int_team_xwalk') }} tx on tx.ws_team_id = s.team_id
